variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ZOLA_VERSION: "v0.8.0"

stages:
  - build
  # - deploy

build:
  stage: build
  script:
    - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
    - tar -xzf zola.tar.gz
    - ./zola build
  artifacts:
    paths:
      - public

deploy:
  image: alpine:latest
  script:
    - apk add openssh sshpass
    - sshpass -p '$DEPLOY_SSH_PASS' ssh $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST "rm -rf /var/customers/webs/timvisee/timvisee.com/*"
    - sshpass -p '$DEPLOY_SSH_PASS' scp public/* $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST:
  dependencies:
  - build
  environment:
    name: production
    url: https://timvisee.com/
  only:
  - deploy
