base_url = "https://timvisee.com"

title = "Tim Visée"
description = "Personal portfolio and blog of Tim Visée"

theme = "zenn"
default_language = "en"

highlight_code = true
highlight_theme = "1337" # or: boron
generate_rss = true
build_search_index = false
check_external_links = false

taxonomies = [
    {name = "categories", paginate_by = 5, rss = true},
    {name = "tags", paginate_by = 5, rss = true},
]

[extra]
author = "Tim Visée"

zenn_title = "Tim Visee"
zenn_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/projects/", name = "Projects"},
    {url = "$BASE_URL/blog/", name = "Blog"},
    {url = "$BASE_URL/about/", name = "About"},
    {url = "$BASE_URL/donate/", name = "Donate"},
    {url = "$BASE_URL/contact/", name = "Contact"},
]
zenn_source = "https://gitlab.com/timvisee/timvisee.com/"
