name = "zenn"
description = "A dark theme for timvisee.com"
license = "GPL-3.0"
homepage = "https://gitlab.com/timvisee/timvisee.com"
min_version = "0.10.0"
demo = "https://timvisee.com/"
version = "0.1.0"

[extra]

[author]
name = "Tim Visée"
homepage = "https://timvisee.com/"
