name = "zenn"
description = "A dark theme for timvisee.com"
license = "AGPL-3.0"
homepage = "https://gitlab.com/timvisee/timvisee.com"
min_version = "0.12.0"
demo = "https://timvisee.com/"
version = "0.2.1"

[extra]

[author]
name = "Tim Visée"
homepage = "https://timvisee.com/"
